apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hyperdisk-arm
  namespace: default
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    - us-central1-a 
    - us-central1-b